# Generated by Django 5.1.4 on 2024-12-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
